### PR TITLE
fix: Add functools.wraps decorator

### PR DESCRIPTION
**Pull request by svleeuwen**
To make sure function attributes are copied to `_http_view_func_wrapper`

### CODE REVIEW

**Comment by anniefu** [comment]
It seems the unit test failures are related to this PR, though it's unclear to me why the change is causing cloudevent functions to fail...

**Comment by svleeuwen** [comment]
@anniefu that test is also failing in master, so it's indeed not caused by this change.

**Comment by anniefu** [comment]
Hmm, it seems one of our dependency libraries has changed their error message causing an assertion to fail. I'll take a pass at fixing it up. Thanks for your patience.

**Review by anniefu — APPROVED** [review]

**Comment by anniefu** [comment]
Hey @svleeuwen, I've fixed the tests up and rebased the PR. Do you have the ability to merge this? I can do it otherwise. Thanks again for the contribution!

**Pull request merged**
