### PR TITLE
ci: don't run when pushing to non-master branches

### PR DESCRIPTION
**Pull request by grant**
This CI PR slightly changes the config to not run on every push.

- Run CI whenever:
  - Pushing to master
  - Pull requests

(Sorry for the extra PR)

### CODE REVIEW

**Comment by di** [comment]
Why? I find it helpful to push a branch and see if CI is passing before I make a PR.

**Comment by grant** [comment]
Oh, if you want to use CI on branches, I suppose that's fine.

There was an issue with producing duplicate test results when pushing to a branch then creating a PR. This was a solution to solve that, heard from one library, but please close this PR if you want CI on branches.

**Comment by grant** [comment]
@di can you comment per https://github.com/GoogleCloudPlatform/functions-framework-python/pull/89#issuecomment-697571433?

Looking for 👍/merge or 👎 /close. I don't care too much which.

**Comment by di** [comment]
> There was an issue with producing duplicate test results when pushing to a branch then creating a PR.

Sorry, not sure I understand. What was the issue?

**Comment by grant** [comment]
https://github.com/GoogleCloudPlatform/functions-framework-python/pull/91/checks

Issue: I sent PR #91 - it has 20 checks. However, 10 checks are duplicative. Would be cool if we can submit PRs and just see the 10 checks.

Screen Shot 2020-09-24 at 11 02 19

Of course this only happens if you use a branch rather than a fork for PRs.

**Comment by grant** [comment]
Ping @di per above comment.

**Comment by di** [comment]
>  Of course this only happens if you use a branch rather than a fork for PRs.

Let's just avoid doing this?

**Pull request closed without merging**
