### PR TITLE
docs: mention flask as the base framework

### PR DESCRIPTION
**Pull request by grant**
Documents the base request framework used for this library.

Fixes https://github.com/GoogleCloudPlatform/functions-framework-python/issues/80
R @anniefu

### CODE REVIEW

**Comment by di** [comment]
I don't think this is sufficient to fix #80? That issue is about documenting the type of the `request` parameter. Linking to the Flask docs is a sort of roundabout way to do it, I'm not sure that would be clear to the average user that this means that the `request` parameter is a Flask `Request` object.

**Comment by grant** [comment]
> I don't think this is sufficient to fix #80? That issue is about documenting the type of the `request` parameter. Linking to the Flask docs is a sort of roundabout way to do it, I'm not sure that would be clear to the average user that this means that the `request` parameter is a Flask `Request` object.

Do you have an idea of how we can fix this?

Should we link this instead?

https://flask.palletsprojects.com/en/1.1.x/api/#flask.request

**Comment by di** [comment]
In #80 I pointed out that we already do this at https://cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python, which says:

> Your function is passed a single parameter, `(request)`, which is a Flask [`Request`](http://flask.pocoo.org/docs/1.0/api/#flask.Request) object.

We could copy/paste this into the docs here, or we could just link to https://cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python which also documents this for background functions as well.

**Comment by grant** [comment]
> In #80 I pointed out that we already do this at [cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python](https://cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python), which says:
> 
> > Your function is passed a single parameter, `(request)`, which is a Flask [`Request`](http://flask.pocoo.org/docs/1.0/api/#flask.Request) object.
> 
> We could copy/paste this into the docs here, or we could just link to [cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python](https://cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python) which also documents this for background functions as well.

Yes, Cloud Functions does talk about this in more detail. However, the Function Frameworks are supposed to be runnable outside of Cloud Functions. I think it's not reasonable to expect users to go find that page, and it's reasonable to talk about the fact Flask is used, especially for new developers. Ruby, Node, other languages state info like this as well.

**Comment by anniefu** [comment]
For me, I'm happy as long as the Flask Request is documented. My two cents here is that we should copy/paste the Flask request bit into this repo.

At the end of the day, Functions Framework decides what the request format is, and the Google Cloud Docs get updated to match, so this repo should be the most up-to-date source of truth.

**Comment by grant** [comment]
@di Can you suggest an alternative way to mention Flask for the user's function handler in the README?

**Comment by di** [comment]
In https://github.com/GoogleCloudPlatform/functions-framework-python/pull/134#issuecomment-858226684 I said that we could copy/paste the following into the docs here from the Cloud Functions docs:

> Your function is passed a single parameter, `(request)`, which is a Flask [`Request`](http://flask.pocoo.org/docs/1.0/api/#flask.Request) object.

Is there any reason that we don't want to do that?

**Review by di — APPROVED** [review]
LGTM, not sure why conformance tests are now failing though.

**Pull request merged**
