### PR TITLE
Include section about Flask routing

### PR DESCRIPTION
**Pull request by thrykol**
Adds documentation around how to set up Flask routing when using functions_framework.

### CODE REVIEW

**Comment by di** [comment]
Hi @thrykol, thanks for the PR. At this time, this isn't a pattern that we want to explicitly support. You're welcome to continue using it but be aware that it may not continue working in exactly the same way in the future. Generally if you need multiple endpoints or routing, we recommend migrating to [Cloud Run](https://cloud.google.com/run) instead.

**Comment by thrykol** [comment]
@di I thought that may be the case so no worries.  My use case is already using `functions_framework` in Cloud Run for Anthos.  Would it make sense to promote the functionality specifically for Cloud Run?

**Comment by di** [comment]
Hi @thrykol, just curious, if you're using Flask's routing features like this as well as Cloud Run, what advantage are you getting from using the Functions Framework as well? You should be able to just deploy the same app to Cloud Run without using Functions Framework as a middleman.

**Comment by thrykol** [comment]
@di I started out in with Python in Cloud Functions but moved to Cloud Run managed and then Cloud Run for Anthos. So between evolution and not having a strong background in Python, functions framework provided a nice abstraction layer.  And once I started using functions framework, new functions ended up using existing ones as a template.  It's only recently that I wanted to make use of routing which resulted in this PR.

**Comment by di** [comment]
Got it! Thanks make sense, thanks for sharing!

**Pull request closed without merging**
